---
title:               "metal & gin"
tagline:             a random collection of thoughts
login:               <%= ENV["obtvse_login"] ? ENV["obtvse_login"] : "username" %>
password:            <%= ENV["obtvse_password"] ? ENV["obtvse_password"] : "password" %>
name:                craig t mackenzie
twitter:             craigtmackenzie
github:              craigtmackenzie
email:               craigtmackenzie@gmail.com
google_analytics_id: YOUR_GA_ID